services:
  - type: web
    name: pounds-comm-backend
    env: node
    plan: free
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000 